package com.mtit.microservices.checkoutservice.controller;

import com.mtit.microservices.checkoutservice.dtos.AddToCartRequest;
import com.mtit.microservices.checkoutservice.dtos.AddToCartResponse;
import com.mtit.microservices.checkoutservice.utils.Cart;
import com.mtit.microservices.checkoutservice.utils.CartRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/addToCart")
public class AddToCartController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CartRepository cartRepository;

    @PostMapping(consumes = "application/json", produces = "application/json")
    public @ResponseBody
    AddToCartResponse item(@RequestBody AddToCartRequest addToCartRequest) {

        System.out.println("Postman Results: " + addToCartRequest);
        var addToCartResponse = new AddToCartResponse();

        //foodId, customerId and itemQty are coming via the Postman JSON Body
        Cart cart = new Cart();
        cart.setFoodId(addToCartRequest.getFoodId());
        cart.setCustomerId(addToCartRequest.getCustomerId());
        cart.setQuantity(addToCartRequest.getQuantity());

        try {
            cartRepository.save(cart);

            addToCartResponse.setStatusMessage("Item is successfully added to the cart.");
            addToCartResponse.setFoodId(addToCartRequest.getFoodId());
            addToCartResponse.setQuantity(addToCartRequest.getQuantity());
            addToCartResponse.setCustomerId(addToCartRequest.getCustomerId());

        }catch (Exception e){
            addToCartResponse.setStatusMessage("There is an issue while adding item to the cart.");
        }

        return addToCartResponse;

    }

}
