package com.mtit.microservices.checkoutservice.controller;

import com.mtit.microservices.checkoutservice.dtos.AddToCartRequest;
import com.mtit.microservices.checkoutservice.dtos.AddToCartResponse;
import com.mtit.microservices.checkoutservice.utils.Cart;
import com.mtit.microservices.checkoutservice.utils.CartRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/addToCart")
public class AddToCartController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CartRepository cartRepository;

    @PostMapping(consumes = "application/json", produces = "application/json")
    public @ResponseBody
    AddToCartResponse item(@RequestBody AddToCartRequest addToCartRequest) {

        System.out.println("Search Results: " + addToCartRequest); //return the postman send request data

        //search on the db and get the values and send to the response

        Cart cart = new Cart();
        cart.setFoodId(addToCartRequest.getFoodId());
        cart.setCustomerId(addToCartRequest.getCustomerId());
        cart.setQuantity(addToCartRequest.getQuantity());
        cartRepository.save(cart);

        var addToCartResponse = new AddToCartResponse();
        addToCartResponse.setQuantity("10");
        addToCartResponse.setTotalPrice("10*24420");



        return addToCartResponse;

    }

}
