package com.mtit.microservices.foodservice.controller;

import com.mtit.microservices.foodservice.dtos.AddFoodRequest;
import com.mtit.microservices.foodservice.dtos.AddFoodResponse;
import com.mtit.microservices.foodservice.utils.Food;
import com.mtit.microservices.foodservice.utils.FoodRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.UUID;


@RestController
@RequestMapping("/addFood")
public class AddFoodServiceController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FoodRepository foodRepository;
    @PostMapping(consumes = "application/json", produces = "application/json")
    public @ResponseBody
    AddFoodResponse item(@RequestBody AddFoodRequest addfoodRequest){

        System.out.println("Food Details: "+ addfoodRequest);

        var addFoodResponse = new AddFoodResponse();

        //foodId,foodName,foodStock ,foodCategory and foodPrice are coming via the Postman JSON Body
        Food food = new Food();

        food.setFoodId(addfoodRequest.getFoodId());
        food.setFoodName(addfoodRequest.getFoodName());
        food.setFoodStock(addfoodRequest.getFoodStock());
        food.setFoodCategory(addfoodRequest.getFoodCategory());
        food.setFoodPrice(addfoodRequest.getFoodPrice());

        try {
            foodRepository.save(food);

            addFoodResponse.setMessage("Food Successfully Added to the System...!!!");
            addFoodResponse.setFoodId(addfoodRequest.getFoodId());
            addFoodResponse.setFoodName(addfoodRequest.getFoodName());
            addFoodResponse.setFoodStock(addfoodRequest.getFoodStock());
            addFoodResponse.setFoodCategory(addfoodRequest.getFoodCategory());
            addFoodResponse.setFoodPrice(addfoodRequest.getFoodPrice());

        }catch (Exception e){
            addFoodResponse.setMessage("There is an issue while adding Food Item To the System");
        }

        return addFoodResponse;

    }

}
