package com.mtit.microservices.foodservice.controller;

import com.mtit.microservices.foodservice.dtos.AddFoodRequest;
import com.mtit.microservices.foodservice.dtos.AddFoodResponse;
import com.mtit.microservices.foodservice.utils.Food;
import com.mtit.microservices.foodservice.utils.FoodRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.UUID;


@RestController
@RequestMapping("/addFood")
public class AddFoodServiceController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FoodRepository foodRepository;
    @PostMapping(consumes = "application/json", produces = "application/json")
    public @ResponseBody
    AddFoodResponse Food(@RequestBody AddFoodRequest foodRequest){

        System.out.println("Food Details: "+ foodRequest);

        var addFoodResponse = new AddFoodResponse();

        //foodId,foodName,foodStock ,foodCategory and foodPrice are coming via the Postman JSON Body
        Food food = new Food();

        food.setFoodName(foodRequest.getFoodName());
        food.setFoodStock(foodRequest.getFoodStock());
        food.setFoodCategory(foodRequest.getFoodCategory());
        food.setFoodPrice(foodRequest.getFoodPrice());

        try {
            foodRepository.save(food);

            addFoodResponse.setMessage("Food Successfully Added to the System...!!!");
            addFoodResponse.setFoodName(addFoodResponse.getFoodName());
            addFoodResponse.setFoodStock(addFoodResponse.getFoodStock());
            addFoodResponse.setFoodCategory(addFoodResponse.getFoodCategory());
            addFoodResponse.setFoodPrice(addFoodResponse.getFoodPrice());

        }catch (Exception e){
            addFoodResponse.setMessage("There is an issue while adding item to the cart.");
        }

        return addFoodResponse;

    }

}
