package com.mtit.microservices.foodservice.controller;

import com.mtit.microservices.foodservice.dtos.AddFoodRequest;
import com.mtit.microservices.foodservice.dtos.AddFoodResponse;
import com.mtit.microservices.foodservice.dtos.UpdateFoodRequest;
import com.mtit.microservices.foodservice.dtos.UpdateFoodResponse;
import com.mtit.microservices.foodservice.utils.Food;
import com.mtit.microservices.foodservice.utils.FoodRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.UUID;

@RestController
@RequestMapping("/updateFood")

public class UpdateFoodServiceController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FoodRepository foodRepository;
        @PutMapping(consumes = "application/json", produces = "application/json")
        public @ResponseBody
        UpdateFoodResponse Food(@RequestBody UpdateFoodRequest updateFoodRequest){

            System.out.println("Update Food Details: "+ updateFoodRequest);

            var updateFoodResponse = new UpdateFoodResponse();
            //foodId,foodName,foodStock ,foodCategory and foodPrice are coming via the Postman JSON Body
            Food food = new Food();

            food.setFoodId(updateFoodRequest.getFoodId());
            food.setFoodName(updateFoodRequest.getFoodName());
            food.setFoodStock(updateFoodRequest.getFoodStock());
            food.setFoodCategory(updateFoodRequest.getFoodCategory());
            food.setFoodPrice(updateFoodRequest.getFoodPrice());

            try {
                foodRepository.save(food);

                updateFoodResponse.setMessage("Food Successfully Updated the System...!!!");
                updateFoodResponse.setFoodId(updateFoodResponse.getFoodId());
                updateFoodResponse.setFoodName(updateFoodResponse.getFoodName());
                updateFoodResponse.setFoodStock(updateFoodResponse.getFoodStock());
                updateFoodResponse.setFoodCategory(updateFoodResponse.getFoodCategory());
                updateFoodResponse.setFoodPrice(updateFoodResponse.getFoodPrice());

            }catch (Exception e){
                updateFoodResponse.setMessage("There is an issue while Updating Food to the System.");
            }

            return updateFoodResponse;

        }

    }



